networks:
  coduels:
    name: coduels
    driver: bridge
    external: true

volumes:
  postgres:

services:
  postgres:
    image: postgres
    container_name: exesh_postgres
    networks:
      - coduels
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: coordinator
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: exesh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coordinator"]
      interval: 1s
      timeout: 0s
      retries: 30
    volumes:
      - postgres:/var/lib/postgresql/data

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    container_name: coordinator
    networks:
      - coduels
    ports:
      - "5253:5253"
    environment:
      CONFIG_PATH: config/coordinator/docker.yml
    depends_on:
      postgres:
        condition: service_healthy
  
  worker-1:
    build:
      context: .
      dockerfile: Dockerfile.worker-1
    container_name: worker-1
    networks:
      - coduels
    ports:
      - "5254:5254"
    environment:
      CONFIG_PATH: config/worker-1/docker.yml

  worker-2:
    build:
      context: .
      dockerfile: Dockerfile.worker-2
    container_name: worker-2
    networks:
      - coduels
    ports:
      - "5255:5255"
    environment:
      CONFIG_PATH: config/worker-2/docker.yml
  
  worker-3:
    build:
      context: .
      dockerfile: Dockerfile.worker-3
    container_name: worker-3
    networks:
      - coduels
    ports:
      - "5256:5256"
    environment:
      CONFIG_PATH: config/worker-3/docker.yml
  
  worker-4:
    build:
      context: .
      dockerfile: Dockerfile.worker-4
    container_name: worker-4
    networks:
      - coduels
    ports:
      - "5257:5257"
    environment:
      CONFIG_PATH: config/worker-4/docker.yml