env: docker
http_server:
  addr: 0.0.0.0:5256
filestorage:
  root_dir: file_storage/worker-3
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
input_provider:
  filestorage_bucket_ttl: 15m
  artifact_ttl: 5m
output_provider:
  artifact_ttl: 5m
worker:
  id: http://worker-3:5256
  free_slots: 4
  coordinator_endpoint: http://coordinator:5253
  heartbeat_delay: 1s
  worker_delay: 1s
