networks:
  coduels:
    name: coduels
    driver: bridge
    external: true

volumes:
  postgres:

services:
  postgres:
    image: postgres:17.7
    container_name: taski_postgres
    networks:
      - coduels
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: taski
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taski
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taski"]
      interval: 1s
      timeout: 0s
      retries: 30
    volumes:
      - postgres:/var/lib/postgresql/data

  taski:
    build: .
    container_name: taski
    networks:
      - coduels
    ports:
      - "5252:5252"
      - "9077:9090"
    environment:
      CONFIG_PATH: /config/docker.yml
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./file_storage:/app/file_storage
      - ./config:/config:ro
