env: dev
http_server:
  addr: localhost:5252
  metrics_addr: 0.0.0.0:9090
filestorage:
  root_dir: file_storage
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
db:
  connection_string: host=localhost port=5434 database=taski user=taski password=secret
  init_timeout: 5m
execute:
  endpoint: http://localhost:5253
  download_task_endpoint: http://localhost:5252
event_consumer:
  brokers:
    - 0.0.0.0:29092
  topic: exesh.step-updates
  group_id: taski
  fetch_interval: 1s
message_producer:
  brokers:
    - 0.0.0.0:29092
  topic: taski.testing
metrics_collector:
  collect_interval: 5s
tasks:
  - 7d971f50363cf0aebbd87d971f50363cf0aebbd8
  - 0c5fe950363fc0aeb7d80c5fe950363fc0aeb7d8
task_topics:
  - структуры данных
  - дерево отрезков