env: docker
http_server:
  addr: 0.0.0.0:5252
filestorage:
  root_dir: file_storage
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
db:
  connection_string: host=taski_postgres port=5432 database=taski user=taski password=secret
  init_timeout: 5m
execute:
  endpoint: http://coordinator:5253
  download_task_endpoint: http://taski:5252
event_consumer:
  brokers:
    - kafka:9092
  topic: exesh.step-updates
  group_id: taski
  fetch_interval: 100ms
message_producer:
  brokers:
    - kafka:9092
  topic: taski.testing
tasks:
  - 7d971f50363cf0aebbd87d971f50363cf0aebbd8
  - 0c5fe950363fc0aeb7d80c5fe950363fc0aeb7d8
  - 26ce3aba327163cd34f7f8fdd9e3c061318912e9
  - 586de7a74de3302ee145a1edbf7bb2befa22f7ff
  - 91ab757e2b7dd3369a7dccd0e367a908c28ceb32
  - 992259beed7308ea89ca514b55d5d474bee335aa
  - ac5266821afb002a0d41912b7a59e3698220151d
  - b63b646d8a5e54a0a75fe8d0dac647d11bc62c1e
  - c611ca79dbe5d03a3e103a45f85ca097167b0a7e
  - d287f1e9bd5e8fca95e91350e5cd23d5e0c9f661