env: dev
http_server:
  addr: localhost:5255
filestorage:
  root_dir: file_storage/worker-2
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
source_provider:
  filestorage_bucket_ttl: 15m
  artifact_ttl: 5m
output_provider:
  artifact_ttl: 5m
worker:
  id: http://localhost:5255
  free_slots: 1
  coordinator_endpoint: http://localhost:5253
  heartbeat_delay: 5s
  worker_delay: 2s
