env: dev
http_server:
  addr: localhost:5253
storage:
  connection_string: host=localhost port=5433 database=exesh user=coordinator password=secret
  init_timeout: 60s
filestorage:
  root_dir: file_storage/coordinator
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
job_factory:
  output:
    compiled_binary: bin
    run_output: output
  source_ttl:
    filestorage_bucket: 30m
    inline: 30m
execution_scheduler:
  executions_interval: 5s
  max_concurrency: 10
  execution_retry_after: 300s
worker_pool:
  worker_die_after: 10s
artifact_registry:
  artifact_ttl: 3m
sender:
  brokers:
    - 0.0.0.0:29092
  topic: exesh.step-updates
