env: docker
http_server:
  addr: 0.0.0.0:5253
  metrics_addr: 0.0.0.0:9090
storage:
  connection_string: host=exesh_postgres port=5432 database=exesh user=coordinator password=secret
  init_timeout: 60s
filestorage:
  root_dir: file_storage/coordinator
  trasher:
    workers: 1
    collector_iterations_delay: 60
    worker_iterations_delay: 5
job_factory:
  output:
    compiled_binary: bin
    run_output: output
  source_ttl:
    filestorage_bucket: 30m
  filestorage_endpoint: http://coordinator:5253
execution_scheduler:
  executions_interval: 3s
  max_concurrency: 10
  execution_retry_after: 30s
worker_pool:
  worker_die_after: 10s
artifact_registry:
  artifact_ttl: 3m
sender:
  brokers:
    - kafka:9092
  topic: exesh.step-updates
